<?php
/**
 * @file
 * Example useage of Drupal Form API module
 */

/**
 * Implements hook_menu().
 */
function drupal_form_api_menu() {
  $items = array();

  $items['admin/settings/drupal_form_api'] = array(
    'title' => 'Drupal Form API Module Settings',
    'description' => 'This page allows you to administer settings for the module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_form_api_admin'),
    'access arguments' => array('administer drupal_form_api settings'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['madlib'] = array(
    'title' => 'Madlib Skeleton',
    'description' => 'Madlib Skeleton Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_form_api_madlib_form'),
    'access arguments' => array('administer drupal_form_api settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * System Setting Form
 */
function drupal_form_api_admin() {
  $form = array();

  $form['drupal_form_api_checkbox'] = array(
    '#type' => 'checkbox',
    '#title' => t('Debug mode'),
    '#default_value' => variable_get('drupal_form_api_checkbox', 0),
    '#description' => t('Turn on/off debug mode'),
  );

  return system_settings_form($form);
}

/**
 * Simple madlib form skeleton
 */
function drupal_form_api_madlib_form($form, &$form_state) {
  
  $form['drupal_form_api_section_1_fieldset'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Section 1'), 
    '#collapsible' => TRUE, 
    '#collapsed' => FALSE,
  );
  
  $form['drupal_form_api_section_1_fieldset']['drupal_form_api_plural_noun_1_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Plural Noun One'),
    '#default_value' => variable_get('drupal_form_api_plural_noun_1_textfield', ''),
    //'#description' => t('Plural Noun One'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_1_fieldset']['drupal_form_api_plural_noun_2_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Plural Noun Two'),
    '#default_value' => variable_get('drupal_form_api_plural_noun_2_textfield', ''),
    //'#description' => t('Plural Noun Two'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_1_fieldset']['drupal_form_api_part_of_body_1_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Part of Body One'),
    '#default_value' => variable_get('drupal_form_api_part_of_body_1_textfield', ''),
    //'#description' => t('Part of Body One'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_2_fieldset'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Section 2'), 
    '#collapsible' => TRUE, 
    '#collapsed' => FALSE,
  );
  
  $form['drupal_form_api_section_2_fieldset']['drupal_form_api_number_select'] = array(
    '#type' => 'select',
    '#title' => t('Number'),
    '#options' => array(
      0 => 1,
      1 => 2,
      2 => 3,
      3 => 4,
      4 => 5,
      5 => 6,
      6 => 7,
      7 => 8,
      8 => 9,
      9 => 10,
    ),
    '#default_value' => variable_get('drupal_form_api_number_select', ''),
    //'#description' => t('Number'),
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_2_fieldset']['drupal_form_api_plural_noun_3_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Plural Noun Three'),
    '#default_value' => variable_get('drupal_form_api_plural_noun_3_textfield', ''),
    //'#description' => t('Plural Noun Three'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_2_fieldset']['drupal_form_api_part_of_body_2_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Part of Body Two'),
    '#default_value' => variable_get('drupal_form_api_part_of_body_2_textfield', ''),
    //'#description' => t('Part of Body Two'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_2_fieldset']['drupal_form_api_type_of_liquid_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Type of Liquid'),
    '#default_value' => variable_get('drupal_form_api_type_of_liquid_textfield', ''),
    //'#description' => t('Type of Liquid'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_2_fieldset']['drupal_form_api_part_of_body_plural_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Part of Body Plural'),
    '#default_value' => variable_get('drupal_form_api_part_of_body_plural_textfield', ''),
    //'#description' => t('Part of Body Plural'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_3_fieldset'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Section 3'), 
    '#collapsible' => TRUE, 
    '#collapsed' => FALSE,
  );
  
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_part_of_body_3_select'] = array(
    '#type' => 'select',
    '#title' => t('Part of Body Three'),
    '#options' => array(
      'head' => array(
        0 => t('eyes'),
        1 => t('nose'),
      ),
      'torso' => array(
        0 => t('stomach'),
      ),
      'legs' => array(
        0 => t('feet'),
      ),
    ),
    '#default_value' => variable_get('drupal_form_api_part_of_body_3_select', ''),
    //'#description' => t('Part of Body Three'),
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_adjective_1_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Adjective One'),
    '#default_value' => variable_get('drupal_form_api_adjective_1_textfield', ''),
    //'#description' => t('Adjective One'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_plural_noun_4_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Plural Noun Four'),
    '#default_value' => variable_get('drupal_form_api_plural_noun_4_textfield', ''),
    //'#description' => t('Plural Noun Four'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
    
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_adjective_2_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Adjective Two'),
    '#default_value' => variable_get('drupal_form_api_adjective_2_textfield', ''),
    //'#description' => t('Adjective Two'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_verb_ing_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Verb_ing'),
    '#default_value' => variable_get('drupal_form_api_verb_ing_textfield', ''),
    //'#description' => t('Verb_ing'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_noun_1_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Noun 1'),
    '#default_value' => variable_get('drupal_form_api_noun_1_textfield', ''),
    //'#description' => t('Noun 1'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
    
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_plural_noun_5_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Plural Noun Five'),
    '#default_value' => variable_get('drupal_form_api_plural_noun_5_textfield', ''),
    //'#description' => t('Plural Noun Five'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_section_3_fieldset']['drupal_form_api_noun_2_textfield'] = array(
    '#type' => 'textfield',
    '#title' => t('Noun Two'),
    '#default_value' => variable_get('drupal_form_api_noun_2_textfield', ''),
    //'#description' => t('Noun Two'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['drupal_form_api_submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#submit' => array('drupal_form_api_madlib_form_submit'),
  );
  
  $form['drupal_form_api_note'] = array(
    '#markup' => '<p>Click it, you know you want to.</p>',
  );
  
  return $form;
}

/**
 * Madlib validate function
 */
function drupal_form_api_madlib_form_validate($form, &$form_state) {
  $verb_ing = $form_state['values']['drupal_form_api_verb_ing_textfield'];
  if (substr($verb_ing, strlen($verb_ing) - 3, 3) != 'ing') {
    form_set_error('drupal_form_api_verb_ing_textfield',
      'Verb_ing: Please enter a word that ends in "ing"');
  }
}

/**
 * Madlib form submit handler
 */
function drupal_form_api_madlib_form_submit($form, &$form_state) {
  drupal_set_message(t('Answers received'));
  $form_state['rebuild'] = TRUE;
}