<?php
/**
 * @file
 * Example usage of Drupal Form API module.
 */

/**
 * Implements hook_menu().
 */
function drupal_form_api_menu() {
  $items = array();

  $items['admin/settings/drupal_form_api'] = array(
    'title' => 'Drupal Form API Module Settings',
    'description' => 'Administer settings for Drupal Form API module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_form_api_admin'),
    'access arguments' => array('administer drupal_form_api settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function drupal_form_api_permission() {
  return array(
    'administer drupal_form_api settings' => array(
      'title' => t('Administer Drupal Form API Settings'),
      'description' => t('Perform administration tasks for Drupal Form API'),
    ),
  );
}


/**
 * Page callback for administration settings.
 */
function drupal_form_api_admin() {
  $form = array();

  $form['drupal_form_api_checkbox'] = array(
    '#type' => 'checkbox',
    '#title' => t('Debug mode'),
    '#default_value' => variable_get('drupal_form_api_checkbox', 0),
    '#description' => t('Turn on/off debug mode'),
  );

  return system_settings_form($form);
}
